# Generated by Django 5.0.6 on 2024-06-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_contadorproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContadorProxy',
        ),
    ]
