# Generated by Django 5.1.3 on 2024-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_delete_contadorproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='pavilhao',
            field=models.CharField(choices=[('1', 'Pavilhão 01'), ('2', 'Pavilhão 02'), ('3', 'Área da Saúde')], max_length=1),
        ),
    ]
