# Generated by Django 5.1.4 on 2024-12-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_sala_pavilhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='nome_personalizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
