# Generated by Django 5.1.3 on 2024-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_ativarpesquisasalas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('pavilhao', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('Medicina', 'Medicina'), ('Outro', 'Outro')], default='Outro', max_length=50)),
            ],
        ),
    ]
