# Generated by Django 5.1.3 on 2024-12-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
