# Generated by Django 5.1.3 on 2024-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(default='Geral', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
