# Generated by Django 5.1.3 on 2024-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_video_categoria_alter_video_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
