# Generated by Django 5.1.3 on 2024-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
